In [1]:
import requests as re
import os
import pandas as pd
import numpy as np
from datetime import timedelta, date

In [2]:
flights = pd.read_csv('flights_2019.csv')

In [3]:
weather_api = os.environ['weather_api_key']

In [22]:
flights.tail()

,fl_date,mkt_unique_carrier,branded_code_share,mkt_carrier,mkt_carrier_fl_num,op_unique_carrier,tail_num,op_carrier_fl_num,origin_airport_id,origin,...,late_aircraft_delay,first_dep_time,total_add_gtime,longest_add_gtime,no_name,dep_hour_num,dep_hour_str,arr_hour_num,arr_hour_str,arr_date
119995,2019-12-01,WN,WN,WN,4721,WN,N961WN,4721,14747,SEA,...,12.0,NaN,NaN,NaN,NaN,22,22,23,23,2019-12-01
119996,2019-12-01,WN,WN,WN,5447,WN,N723SW,5447,14747,SEA,...,0.0,NaN,NaN,NaN,NaN,6,6,8,8,2019-12-01
119997,2019-12-01,WN,WN,WN,5021,WN,N739GB,5021,14747,SEA,...,NaN,NaN,NaN,NaN,NaN,9,9,15,15,2019-12-01
119998,2019-12-01,WN,WN,WN,5841,WN,N8549Z,5841,14771,SFO,...,NaN,NaN,NaN,NaN,NaN,5,5,10,10,2019-12-01
119999,2019-12-01,WN,WN,WN,2044,WN,N7839A,2044,14771,SFO,...,NaN,NaN,NaN,NaN,NaN,8,8,9,9,2019-12-01

In [28]:
flights['fl_date'].nunique()

31

In [4]:
dates_list = flights['fl_date'].unique().tolist()

In [34]:
dates_list2 = dates_list[20:]

In [5]:
airport_list = flights['origin'].unique().tolist()

In [36]:
len(airport_list)

369

In [58]:
arr_list= flights['arr_date'].unique().tolist()

In [75]:
arr_list = arr_list[11:]

In [50]:
dest_list = flights['dest'].unique().tolist()

In [52]:
len(arr_dates)

39

In [35]:
'''condition_list = []
for date in dates_list2:
    for airport in airport_list:
        url = 'http://api.weatherapi.com/v1/history.json?key='+weather_api+'&q='+airport+'&dt='+date+'&hour='+'12'
        r = re.get(url)
        res = r.json()
        temp_list = [date,airport,res['forecast']['forecastday'][0]['hour'][0]['condition']['text']]
        condition_list.append(temp_list)'''

In [48]:
'''arr_dates = pd.to_datetime(flights['fl_date'])
for date in range(len(arr_date)):
    if flights['crs_dep_time'][date] > flights['crs_arr_time'][date]:
        arr_date[date] = arr_date[date] + timedelta(days=1)
flights['arr_date'] = arr_date
flights['arr_date'] = flights['arr_date'].astype(str)'''

In [76]:
arr_condition_list = []
for date in arr_list:
    for airport in dest_list:
        url = 'http://api.weatherapi.com/v1/history.json?key='+weather_api+'&q='+airport+'&dt='+date+'&hour='+'12'
        r = re.get(url)
        res = r.json()
        temp_list = [date,airport,res['forecast']['forecastday'][0]['hour'][0]['condition']['text']]
        arr_condition_list.append(temp_list)

In [77]:
len(arr_condition_list)

10332

In [72]:
arr_condition_list1 = arr_condition_list[:4058]

In [89]:
arr_condition_df = pd.DataFrame(data=arr_condition_list3,columns=['arr_date','dest', 'arr_condition'])

In [78]:
arr_condition_list2 = arr_condition_list

In [82]:
arr_condition_list3 = arr_condition_list1+arr_condition_list2

In [88]:
len(arr_condition_list3)

14390

In [40]:
len(condition_list2)

4059

In [37]:
len(condition_list1)

7380

In [41]:
fcondition_list = condition_list1+condition_list2

In [42]:
len(fcondition_list)

11439

In [43]:
condition_df = pd.DataFrame(data=fcondition_list,columns=['fl_date','origin', 'dep_condition'])

In [44]:
condition_df

          fl_date origin  dep_condition
0      2019-01-01    ORD       Overcast
1      2019-01-01    MYR         Cloudy
2      2019-01-01    BDL          Sunny
3      2019-01-01    DCA          Sunny
4      2019-01-01    ORF  Partly cloudy
...           ...    ...            ...
11434  2019-12-03    PPG          Sunny
11435  2019-12-03    ACK       Blizzard
11436  2019-12-03    MVY       Blizzard
11437  2019-12-03    HYA       Blizzard
11438  2019-12-03    XWA          Sunny

[11439 rows x 3 columns]

In [90]:
flights_weather2 = flights_weather.merge(arr_condition_df,how='left',on=['arr_date','dest'] )

In [55]:
flights_weather['arr_date']=flights['arr_date']

In [56]:
flights_weather

,fl_date,mkt_unique_carrier,branded_code_share,mkt_carrier,mkt_carrier_fl_num,op_unique_carrier,tail_num,op_carrier_fl_num,origin_airport_id,origin,...,weather_delay,nas_delay,security_delay,late_aircraft_delay,first_dep_time,total_add_gtime,longest_add_gtime,no_name,dep_condition,arr_date
0,2019-01-01,AA,AA_CODESHARE,AA,3044,OO,N761ND,3044,13930,ORD,...,0.0,6.0,0.0,0.0,NaN,NaN,NaN,NaN,Overcast,2019-01-01
1,2019-01-01,AA,AA_CODESHARE,AA,5606,OH,N575NN,5606,13577,MYR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cloudy,2019-01-01
2,2019-01-01,AA,AA_CODESHARE,AA,5607,OH,N254PS,5607,10529,BDL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sunny,2019-01-01
3,2019-01-01,AA,AA_CODESHARE,AA,5607,OH,N254PS,5607,11278,DCA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sunny,2019-01-01
4,2019-01-01,AA,AA_CODESHARE,AA,5608,OH,N710PS,5608,11278,DCA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sunny,2019-01-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119995,2019-12-01,WN,WN,WN,4721,WN,N961WN,4721,14747,SEA,...,0.0,5.0,0.0,12.0,NaN,NaN,NaN,NaN,Overcast,2019-12-01
119996,2019-12-01,WN,WN,WN,5447,WN,N723SW,5447,14747,SEA,...,0.0,6.0,0.0,0.0,NaN,NaN,NaN,NaN,Overcast,2019-12-01
119997,2019-12-01,WN,WN,WN,5021,WN,N739GB,5021,14747,SEA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Overcast,2019-12-01
119998,2019-12-01,WN,WN,WN,5841,WN,N8549Z,5841,14771,SFO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Moderate rain,2019-12-01
119999,2019-12-01,WN,WN,WN,2044,WN,N7839A,2044,14771,SFO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Moderate rain,2019-12-01

In [91]:
flights_weather2.to_csv('flights_2019_weather_full.csv',index=False)

In [27]:
flights['origin'].nunique()

369

In [92]:
df = pd.read_csv('flights_2019_weather_full.csv')

In [93]:
df

,fl_date,mkt_unique_carrier,branded_code_share,mkt_carrier,mkt_carrier_fl_num,op_unique_carrier,tail_num,op_carrier_fl_num,origin_airport_id,origin,...,nas_delay,security_delay,late_aircraft_delay,first_dep_time,total_add_gtime,longest_add_gtime,no_name,dep_condition,arr_date,arr_condition
0,2019-01-01,AA,AA_CODESHARE,AA,3044,OO,N761ND,3044,13930,ORD,...,6.0,0.0,0.0,NaN,NaN,NaN,NaN,Overcast,2019-01-01,Partly cloudy
1,2019-01-01,AA,AA_CODESHARE,AA,5606,OH,N575NN,5606,13577,MYR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cloudy,2019-01-01,Sunny
2,2019-01-01,AA,AA_CODESHARE,AA,5607,OH,N254PS,5607,10529,BDL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sunny,2019-01-01,Sunny
3,2019-01-01,AA,AA_CODESHARE,AA,5607,OH,N254PS,5607,11278,DCA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sunny,2019-01-01,Sunny
4,2019-01-01,AA,AA_CODESHARE,AA,5608,OH,N710PS,5608,11278,DCA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sunny,2019-01-01,Partly cloudy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119995,2019-12-01,WN,WN,WN,4721,WN,N961WN,4721,14747,SEA,...,5.0,0.0,12.0,NaN,NaN,NaN,NaN,Overcast,2019-12-01,Moderate rain
119996,2019-12-01,WN,WN,WN,5447,WN,N723SW,5447,14747,SEA,...,6.0,0.0,0.0,NaN,NaN,NaN,NaN,Overcast,2019-12-01,Moderate rain
119997,2019-12-01,WN,WN,WN,5021,WN,N739GB,5021,14747,SEA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Overcast,2019-12-01,Blizzard
119998,2019-12-01,WN,WN,WN,5841,WN,N8549Z,5841,14771,SFO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Moderate rain,2019-12-01,Sunny
119999,2019-12-01,WN,WN,WN,2044,WN,N7839A,2044,14771,SFO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Moderate rain,2019-12-01,Sunny

In [29]:
flights['dest'].nunique()

369

In [8]:
flights['dep_hour_num']= flights['crs_dep_time']//100
flights['dep_hour_str'] = flights['dep_hour_num'].astype(str)
flights['arr_hour_num']= flights['crs_arr_time']//100
flights['arr_hour_str'] = flights['arr_hour_num'].astype(str)

In [14]:
dep_condition = []
for x in range(len(flights)):
    url = 'http://api.weatherapi.com/v1/history.json?key='+weather_api+'&q='+flights['origin'][x]+'&dt='+flights['fl_date'][x]+'&hour='+flights['dep_hour_str'][x]
    r = re.get(url)
    res = r.json()  
    dep_condition.append(res['forecast']['forecastday'][0]['hour'][0]['condition']['text'])
flights['dep_condition'] = dep_condition

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

In [18]:
flights['dep_condition'] = dep_condition

ValueError: Length of values (11864) does not match length of index (120000)

In [17]:
len(dep_condition)

11864

In [23]:
arr_condition = []
for x in range(len(flights)):
    url = 'http://api.weatherapi.com/v1/history.json?key='+weather_api+'&q='+flights['dest'][x]+'&dt='+flights['arr_date'][x]+'&hour='+flights['arr_hour_str'][x]
    r = re.get(url)
    res = r.json()  
    arr_condition.append(res['forecast']['forecastday'][0]['hour'][0]['condition']['text'])
flights['arr_condition'] = arr_condition

KeyboardInterrupt:

In [15]:
flights.head()

,fl_date,mkt_unique_carrier,branded_code_share,mkt_carrier,mkt_carrier_fl_num,op_unique_carrier,tail_num,op_carrier_fl_num,origin_airport_id,origin,...,late_aircraft_delay,first_dep_time,total_add_gtime,longest_add_gtime,no_name,dep_hour_num,dep_hour_str,arr_hour_num,arr_hour_str,arr_date
0,2019-01-01,AA,AA_CODESHARE,AA,3044,OO,N761ND,3044,13930,ORD,...,0.0,NaN,NaN,NaN,NaN,9,9,11,11,2019-01-01
1,2019-01-01,AA,AA_CODESHARE,AA,5606,OH,N575NN,5606,13577,MYR,...,NaN,NaN,NaN,NaN,NaN,21,21,23,23,2019-01-01
2,2019-01-01,AA,AA_CODESHARE,AA,5607,OH,N254PS,5607,10529,BDL,...,NaN,NaN,NaN,NaN,NaN,11,11,13,13,2019-01-01
3,2019-01-01,AA,AA_CODESHARE,AA,5607,OH,N254PS,5607,11278,DCA,...,NaN,NaN,NaN,NaN,NaN,10,10,11,11,2019-01-01
4,2019-01-01,AA,AA_CODESHARE,AA,5608,OH,N710PS,5608,11278,DCA,...,NaN,NaN,NaN,NaN,NaN,20,20,21,21,2019-01-01

In [21]:
len(arr_condition)

654

In [24]:
len(arr_condition)

2021